# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{arpi_gem_builder}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["reddavis"]
  s.date = %q{2010-09-09}
  s.description = %q{Turn API documentation into working code}
  s.email = %q{reddavis@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "arpi_gem_builder.gemspec",
     "example/play_documentation.html",
     "lib/arpi_gem_builder.rb",
     "lib/arpi_gem_builder/base_http_file.rb",
     "lib/arpi_gem_builder/base_lib_file.rb",
     "lib/arpi_gem_builder/http_resource_file.rb",
     "lib/arpi_gem_builder/method_builder.rb",
     "lib/arpi_gem_builder/templates/base_http_file.erb",
     "lib/arpi_gem_builder/templates/base_lib_file.erb",
     "lib/arpi_gem_builder/templates/http_resource_file.erb",
     "test/arpi_gem_builder/test_base_http_file.rb",
     "test/arpi_gem_builder/test_base_lib_file.rb",
     "test/arpi_gem_builder/test_http_resource_file.rb",
     "test/arpi_gem_builder/test_method_builder.rb",
     "test/fixtures/embedit_api.html",
     "test/helper.rb",
     "test/test_arpi_gem_builder.rb"
  ]
  s.homepage = %q{http://github.com/reddavis/arpi_gem_builder}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Turn API documentation into working code}
  s.test_files = [
    "test/arpi_gem_builder/test_base_http_file.rb",
     "test/arpi_gem_builder/test_base_lib_file.rb",
     "test/arpi_gem_builder/test_http_resource_file.rb",
     "test/arpi_gem_builder/test_method_builder.rb",
     "test/helper.rb",
     "test/test_arpi_gem_builder.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, ["~> 1.4.0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.4.0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.4.0"])
  end
end

